spring:
  application:
    name: JEJA-BE
    # ?????? ?? ?? (Datasource)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  # JPA (Java Persistence API) ??
  jpa:
    # Hibernate ??
    hibernate:
      # ddl-auto: Entity ???? ???? DB ???? ???? ??/??
      #   - create: ?? ??? ?? ??? ?? ? ?? ?? (????)
      #   - update: ??? ??? ?? (???)
      #   - validate: Entity? ???? ????? ??
      #   - none: ???? ?? ?? (???)
      ddl-auto: update

    # JPA ?? ?? ????
    properties:
      hibernate:
        # ???? SQL ??? ?? ?? ??
        format_sql: true
        # ??? ?????? ??(Dialect) ??
        dialect: org.hibernate.dialect.MariaDBDialect

    # ??? ???? SQL ???? ???
    show-sql: true

# ?? ?? ??
server:
  port: 8080
